services:
  vibe:
    image: ghcr.io/contenox/vibe:v0.0.76
    container_name: contenox-vibe-kernel
    environment:
      - DATABASE_URL=postgres://username:password@postgres:5432/postgres?sslmode=disable
      - PORT=8080
      - NATS_URL=nats://natsuser:natspassword@nats:4222
      - NATS_USER=natsuser
      - NATS_PASSWORD=natspassword
      - TOKENIZER_SERVICE_URL=http://tokenizer:50051
      - EMBED_MODEL=${EMBED_MODEL}
      - EMBED_PROVIDER=${EMBED_PROVIDER}
      - EMBED_MODEL_CONTEXT_LENGTH=${EMBED_MODEL_CONTEXT_LENGTH}
      - TASK_MODEL=${TASK_MODEL}
      - TASK_MODEL_CONTEXT_LENGTH=${TASK_MODEL_CONTEXT_LENGTH}
      - TASK_PROVIDER=${TASK_PROVIDER}
      - CHAT_MODEL=${CHAT_MODEL}
      - CHAT_MODEL_CONTEXT_LENGTH=${CHAT_MODEL_CONTEXT_LENGTH}
      - CHAT_PROVIDER=${CHAT_PROVIDER}
      # - TOKEN=your_token_here
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/health || exit 1"]
      interval: 1s
      timeout: 1s
      retries: 20

  tokenizer:
    image: ghcr.io/contenox/ollamatokenizer-api:v0.0.9
    container_name: contenox-ollama-tokenizer
    environment:
      - PRELOAD_MODELS=phi-3,granite-embedding-30m,tiny
      - TOKENIZER_TIMEOUT=30s
      - FALLBACK_MODEL=granite-embedding-30m
      - USE_DEFAULT_URLS=true
      - ADDR=:50051
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:50051/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:17-bookworm
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    command: "-js"
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_USER=natsuser
      - NATS_PASSWORD=natspassword

  ollama:
    image: ollama/ollama:0.1.44
    ports:
      - "11435:11434"
    # volumes:
    #   - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
  echo:
    image: ghcr.io/contenox/contenox/hook-echo:v0.3.1
    container_name: contenox-echo
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000/health || exit 1"]
      interval: 1s
      timeout: 1s
      retries: 20
# volumes:
#   postgres-data:
#   ollama-data:
